[package]
name = "rust-bitcoin-keygen"
version = "1.0.0"
edition = "2024"

[dependencies]
secp256k1 = { version = "0.28", features = ["rand-std"] }
rustc-hash = "2.1.1"
ripemd = "0.1"
base58 = "0.2"
ctrlc = "3.4"
sha2 = "0.10"
bs58 = "0.4"
